# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

In [1]:
import numpy as np

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [2]:
data = np.loadtxt('minutes_n_ingredients.csv', dtype = 'int32', delimiter = ',', skiprows = 1)

In [23]:
data[:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [39]:
print ('Минимум по 2ому столбцу:', np.min(data[:,1]),'\n'
       'Минимум по 3ему столбцу:', np.min(data[:,2]),'\n' 
       'Максимум по 2ому столбцу:', np.max(data[:,1]),'\n' 
       'Максимум по 3ему столбцу:', np.max(data[:,2]),'\n' 
       'Медиана по 2ому столбцу:', np.median(data[:,1]),'\n' 
       'Медиана по 3ему столбцу:', np.median(data[:,2]))

Минимум по 2ому столбцу: 0 
Минимум по 3ему столбцу: 1 
Максимум по 2ему столбцу: 2147483647 
Максимум по 3ему столбцу: 39 
Медиана по 2ему столбцу: 40.0 
Медиана по 3ему столбцу: 9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [53]:
print('Массив, ограниченный сверху 75%-м квантилем по столбцу со временем:',
      (data[:,1][data[:,1] < np.quantile(data[:,1], 0.75)]), '\n'
      'Количество значений, которые попали в этот диапазон:', 
      len((data[:,1][data[:,1] < np.quantile(data[:,1], 0.75)])), '\n'
      'Значение квантиля по столбцу со временем:', np.quantile(data[:,1], 0.75)) 

Массив, ограниченный сверху 75%-м квантилем по столбцу со временем: [60 25 10 ... 35 35  5] 
Количество значений, которые попали в этот диапазон: 73106 
Значение квантиля по столбцу со временем: 65.0


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [69]:
#data_time_zero = np.size(data[:,1][data[:,1] == 0]) Для того что бы посчитать сколько значений 0 (479)
#data_time_one = np.size(data[:,1][data[:,1] == 1]) Для того что бы посчитать сколько значений 1 (237)
time_zero = data[:,1][data[:,1] == 0]

In [74]:
time_zero_to_one = (np.where([data[:,1] == 0], 1, data[:,1]))

In [78]:
np.size(time_zero_to_one[time_zero_to_one == 1]) # Проверка что все значения 0 стали 1 (479+237 = 716)

716

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [82]:
np.size(np.unique(data[:,1:]))

656

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [89]:
print(np.size(np.unique(data[:,2])))
print(np.unique(data[:,2]))

37
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [96]:
less_five_ingred = data[data[:,2] <= 5]

In [99]:
np.max(less_five_ingred[:,2]) # для проверки что максимальное значение теперь 5

5

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [115]:
(data[:,2] / np.where(data[:,1] == 0, 1, data[:,1]))
# т.к. в некоторых случаях встречается 0 минут, меняем 0 на единицу, чтобы не было ошибки

array([0.26666667, 0.28      , 0.6       , ..., 0.23076923, 0.8       ,
       0.1       ])

In [117]:
np.max(data[:,2] / np.where(data[:,1] == 0, 1, data[:,1]))

24.0

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [121]:
np.mean(data[:,2])

9.05528

In [125]:
np.sort(data[:,1])

array([         0,          0,          0, ...,     259205,     259260,
       2147483647])

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [9]:
a = np.random.randint(10, size=10)

In [10]:
data[a,:]

array([[157911,     60,     14],
       [ 94746,     10,      6],
       [157911,     60,     14],
       [ 74205,     20,      7],
       [ 67660,      5,      6],
       [366174,      7,      9],
       [446597,     15,      5],
       [152828,     40,      7],
       [ 33941,     18,      9],
       [446597,     15,      5]])

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [31]:
np.shape(data[data[:,2] < np.mean(data[:,2])])[0]/np.shape(data)[0]*100

58.802

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [35]:
data_simple = np.insert(data, 3, values=np.where((data[:,1] <= 20) & (data[:,2] <= 5), 1, 0), axis=1)

In [36]:
data_simple

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ..., 
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]])

In [37]:
data_simple.shape

(100000, 4)

In [38]:
data.shape

(100000, 3)

In [11]:
# data_simple[:,3] = np.where((data_simple[:,1] <= 20) & (data_simple[:,2] <= 5), 1, 0)

13. Выведите процент "простых" рецептов в датасете

In [40]:
np.shape(data_simple[data_simple[:,3] == 1])[0]/np.shape(data_simple)[0]*100

9.552

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [43]:
data_short = data[data[:,1] < 10]

In [46]:
data_standart = data[(data[:,1] > 10) & (data[:,1] < 20)]

In [48]:
data_long = data[data[:,1] >= 20]